title: 'President''s Challenge'
title-abbreviated: 'President''s Challenge'
description: 'President''s Challenge. Empowering Lives, Uplifting Communities.'
url: 'https://www.presidentschallenge.gov.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
collections:
    left-nav-one:
        output: true
    left-nav-two:
        output: true
    left-nav-three:
        output: true
    left-nav-four:
        output: true
resources_name: resource-room
favicon: /images/favicon.ico
google_analytics: UA-2833102-27
permalink: none
baseurl: ""
defaults:
    - scope:
          path: ""
      values:
          layout: page
